### ISSUE TITLE
Re-license to MIT

### ISSUE THREAD

**Issue by simon04** [jacopotarantino/angular-match-media#23]
Having a CC license is rather atypical for software. Requiring attribution for a small module makes it difficult to use in some contexts.

Angular it self and many modules are licensed under the MIT license. Please consider to re-license your module and also provided it under the MIT license!

**Comment by jacopotarantino** [comment]
@simon04 While I'm a big fan of free and open-source software, I'd like for my software to go out under some manner of license that's slightly less permissive than a "do what you want" license as some small manner of protection for myself. In any case in which someone feels that they can't reasonably use this software given the published license, I would encourage them to reach out to me directly and I would grant them permission to circumvent whatever part of that license they find encumbering. In the future I would likely relicense everything as beerware but I like having my name on things for now.

If you can think of a more compelling reason for me to relicense or if you think that rationale is insufficient, please let me know! I'm definitely open to being challenged on this one and spent a bit of time thinking about it before responding. Otherwise closing this one for now.
