### ISSUE TITLE
Watch off

### ISSUE THREAD

**Issue by SamanthaAdrichem** [jacopotarantino/angular-match-media#38]
Since screenSize.on is probably a watch, is there also a screenSize.off?

**Comment by jacopotarantino** [comment]
There is not. You could reasonably wrap the `on` function and create a second listener with `on` that then checks for the current value to change. If you'd like to create a PR adding the `off` method I'd be happy to approve it. Otherwise, any future development is going toward an Angular2 version of the plugin. Hope that helps! Feel free to re-open if you have further questions.
